import { SceneArt } from "@/components/art/SceneArt";
import { hasBitmap } from "@/lib/manifest";
import type { ImageAsset } from "@/lib/manifest/types";

type SceneMode = "hero" | "card" | "portrait" | "tile" | "fill";

/**
 * Renders an approved bitmap when one exists, otherwise the layered vector
 * scene for the same slot. Either way the element has explicit intrinsic
 * dimensions or a fixed aspect ratio so nothing shifts as the page loads
 * (spec §59, layout shift under 0.1).
 *
 * A non-empty `alt` becomes the accessible name of the whole picture; an empty
 * `alt` marks it decorative and hides it from assistive technology (spec §61).
 */
export function SceneImage({
  asset,
  mode = "card",
  className = "",
  priority = false,
}: {
  asset: ImageAsset;
  mode?: SceneMode;
  className?: string;
  priority?: boolean;
}) {
  const describable = asset.alt.trim().length > 0;

  if (hasBitmap(asset)) {
    return (
      // eslint-disable-next-line @next/next/no-img-element -- responsive sources are pre-generated by the asset pipeline; no runtime optimiser is in play.
      <img
        src={asset.src}
        alt={asset.alt}
        width={asset.width}
        height={asset.height}
        loading={priority ? "eager" : "lazy"}
        decoding="async"
        fetchPriority={priority ? "high" : "auto"}
        className={`h-full w-full object-cover ${className}`}
      />
    );
  }

  return (
    <div
      className={`${mode === "fill" ? "h-full w-full" : ""} ${className}`}
      {...(describable
        ? { role: "img", "aria-label": asset.alt }
        : { "aria-hidden": true as const })}
    >
      <SceneArt artwork={asset.artwork} uid={asset.id} mode={mode} />
    </div>
  );
}
